### ISSUE TITLE
First charactor does not match

### ISSUE THREAD

**Issue by ryicoh** [hrsh7th/vim-searchx#2]
<img width="382" alt="スクリーンショット 2021-12-31 1 36 21" src="https://user-images.githubusercontent.com/37844673/147773113-06bb1522-4020-40c4-9bb5-05ca0d601e78.png">

**Comment by hrsh7th** [comment]
@ryicoh What is the your `g:searchx.convert`?

**Comment by ryicoh** [comment]
@hrsh7th Here!
```vim 
function g:searchx.convert(input) abort
  if a:input !~# '\k'
    return '\V' .. a:input
  endif
  let l:sep = a:input[0] =~# '[[:alnum:]]' ? '[^[:alnum:]]\zs' : '[[:alnum:]]\zs'
  return l:sep .. join(split(a:input, ' '), '.\{-}')
endfunction

```

Same as example(https://github.com/hrsh7th/vim-searchx#settings).

**Comment by hrsh7th** [comment]
@ryicoh I've updated the README.md. Please try it.

**Comment by ryicoh** [comment]
<img width="327" alt="スクリーンショット 2021-12-31 2 41 56" src="https://user-images.githubusercontent.com/37844673/147775584-a2db5df8-885d-4297-a531-d21f9b1078f5.png">

It does not working.

**Comment by ryicoh** [comment]
if turn off fuzzy matching, it seems to work.
```vim
function g:searchx.convert(input) abort
  return a:input
endfunction
```
@hrsh7th

**Comment by hrsh7th** [comment]
This plugin does not have fuzzy matching feature anymore. (I've removed the feature).

**Comment by hrsh7th** [comment]
The README.md and the sample in the help means fuzzy matching with a space character.

https://user-images.githubusercontent.com/629908/147776187-336c949a-8c95-4e07-b5da-daf298ce56f6.mp4

**Comment by ryicoh** [comment]
<img width="417" alt="スクリーンショット 2021-12-31 3 18 16" src="https://user-images.githubusercontent.com/37844673/147778131-1b730c71-0ea0-4f06-8682-b492a8b937e9.png">

Sorry I could not understand the vim regexps in README.md, but converted value(`/[^[:alnum:]]\zsca`) did not match `call` in line 3.

**Comment by hrsh7th** [comment]
I've re-update the README.md.
